[package]
name = "rumu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.26.0"
json = "0.12.0"
md5 = "0.7.0"
crossterm = "0.23.0"
tui = "0.18.0"
walkdir = "2.3.0"
sha1 = "0.10.0"
